pt-plugins/PT-depiler

- src/packages/site/definitions/sjtu.ts
> feat(site/sjtu): 支持发种数、做种数、做种体积

- src/packages/site/definitions/totheglory.ts
- src/packages/site/types/userinfo.ts
将 uploads 加入到了 IUserInfo, 这样以后就可以直接使用选择器了
> fix(site/TTG): 支持发种数量

- src/packages/site/definitions/audiences.ts
已支持搜索和大部分数据的获取。
但做种数、做种体积与发布数需要支持 Referer 替换后才能获得，V2 中的替换方法在 V3 中弃用了。
> feat(adapter\site): 支持 Audiences

- src/packages/site/definitions/pter.ts
pt-plugins/PT-Plugin-Plus#2218
顺带修复一下 status 与 progress 获取（估计是笔误了）
> feat(adapter\site): 支持统计 pter 站点已初审状态的发种数

- src/packages/site/definitions/btschool.ts
- src/packages/site/definitions/byrbt.ts
- src/packages/site/definitions/hddolby.ts
- src/packages/site/definitions/springsunday.ts
- src/packages/site/definitions/tjupt.ts
- src/packages/site/definitions/totheglory.ts
> fix(pkg/site): 修复多个站点的时魔统计

- src/packages/site/definitions/cyanbug.ts
- src/packages/site/definitions/hdfans.ts
- src/packages/site/definitions/u2.ts
> feat(pkg/site): 站点适配 Cyanbug & HDFans

- src/entries/options/views/Overview/MyData/Index.vue
偶然发现点击刷新按钮后，数据更新了，但是页面没有更新，不太熟悉这个项目的写法，因此加了一个改动最小的方案上去，如有冲突或不符合开发规范请指出
> 修复刷新站点页面数据不更新

- src/packages/site/definitions/soulvoice.ts
> feat(pkg/site): 站点 SoulVoice 完善等级数据

- src/packages/site/definitions/pthome.ts
> feat(pkg/site): 站点 PTHome 完善等级数据

- src/packages/site/definitions/zhuque.ts
> feat(pkg/site): 站点适配 ZHUQUE （初步）

- src/packages/site/definitions/1ptba.ts
- src/packages/site/definitions/52pt.ts
- src/packages/site/definitions/azusa.ts
- src/packages/site/definitions/carpt.ts
- src/packages/site/definitions/filelist.ts
- src/packages/site/definitions/freefarm.ts
- src/packages/site/definitions/greatposterwall.ts
- src/packages/site/definitions/haidan.ts
- src/packages/site/definitions/hdarea.ts
- src/packages/site/definitions/hdcity.ts
- src/packages/site/definitions/hhanclub.ts
- src/packages/site/definitions/hitpt.ts
- src/packages/site/definitions/htpt.ts
- src/packages/site/definitions/wintersakura.ts
- src/packages/site/definitions/zmpt.ts
fix(pkg/site): 优化憨憨站点等级名称获取
fix(pkg/site): 部分站点增加user级别
> fix(pkg/site): 优化憨憨站点等级名称获取

- src/entries/options/views/Devtools/Debugger.vue
> feat(Debugger): 支持清空单一站点的用户数据

- src/packages/site/definitions/pttime.ts
refs: https://github.com/pt-plugins/PT-depiler/pull/136#issuecomment-2962542652
> fix(pkg/site): 修复 PTT 的 levelName、seeding、seedingSize

- src/packages/site/definitions/dicmusic.ts
- src/packages/site/definitions/opencd.ts
- src/packages/site/schemas/GazelleJSONAPI.ts
- src/packages/site/utils/level.ts
level.ts
> 增加对"perfectFlacs", "groups", "specialSeedingSize"字段判断
GazelleJSONAPI.ts
> 增加对促销tags
opencd.ts
> color: "deep-orange-darken-1" // 禁转
> feat(pkg/site): 重新适配DICMusic

- src/packages/site/definitions/kelu.ts
> feat(pkg/site): add kelu

- src/entries/options/views/Overview/MyData/Index.vue
- src/packages/site/definitions/huno.ts
更好地显示“点击站点图标刷新数据”的功能
Others: 
fix(pkg/site): 修复 HUNO 站点的 hnrPreWarning 计数
> feat(MyData): 站点图标处添加鼠标指针样式与 hover

- src/packages/site/definitions/blutopia.ts
- src/packages/site/utils/filter.ts
> feat(pkg/site): add blutopia

- src/packages/site/definitions/pttime.ts
修复 仅能获取一条搜索结果 的问题
看起来是没有正确获取到 “id” 导致
> fix(pkg/site): fix selectors for PTT search.

- src/packages/site/definitions/hdhome.ts
Update the bonusPerHour selector to use a more specific query and improve the calculation logic by aggregating text from relevant div elements.
> Fix bonusPerHour selector and calculation logic

- src/packages/site/definitions/azusa.ts
应站点要求取消用户信息获取
refs: https://t.me/c/1276598895/137893
> fix(pkg/site): 修复asuza可以获取用户信息的bug

- src/packages/site/definitions/hxpt.ts
> feat(pkg/site): 站点适配 好学PT

- src/packages/site/definitions/hdsky.ts
> fix(空): 添加站点的奖励积分设置

- src/packages/mediaServer/entity/plex.ts
fix: https://github.com/pt-plugins/PT-depiler/issues/350
> fix: 修复plex媒体访问链接

- src/packages/site/utils/level.ts
> fix(level): 修复部分站点的 levelId 匹配出错

- src/entries/options/views/Layout/Topbar.vue
- src/entries/options/views/Overview/MyData/UserLevelRequirementsTd.vue
> fix(UI): 添加 tooltip 组件的点击打开行为

- src/packages/site/utils/level.ts
> fix(level): 修正 levelRequirementUnMet 函数中 alternativeUnMet 的逻辑判断

- src/entries/options/views/Overview/MyData/UserDataStatistic/Index.vue
> fix(UserDataStatistic): 修复分站点做种数图表

- src/packages/site/definitions/asmrpt.ts
closed: https://github.com/pt-plugins/PT-depiler/issues/450
> feat(pkg/site): 使用NPHP默认适配站点 asmrpt

- src/entries/options/views/Overview/MyData/UserDataStatistic/utils.ts
优化总结
现在的解决方案更加简洁和高效：
主要优化点
移除了复杂的自定义函数：
删除了 minDateString、maxDateString 和 generateDateRange 函数
直接使用 JavaScript 原生的 Array.sort() 方法
利用 yyyy-MM-dd 格式的天然优势：
yyyy-MM-dd 格式天然支持字典序排序
['2023-01-01', '2023-12-31', '2023-06-15'].sort() 会得到正确的时间顺序
最小化时区影响：
在创建 Date 对象时明确指定时间为 T00:00:00
只在必要时创建 Date 对象（用于 eachDayOfInterval）
保持代码简洁：
减少了代码行数
提高了可读性
降低了维护成本
核心改进
第63-66行：直接排序数组获取最小最大值
第76-82行：在站点循环中使用相同的简洁方法
第128-131行：setSubDate 函数恢复原有的简洁实现
这样既解决了时区问题，又保持了代码的简洁性。yyyy-MM-dd 格式的字符串排序就能得到正确的时间顺序，无需复杂的日期处理逻辑。
> fix(UserDataStatistic): 修复日期范围计算因为时区换算导致错误

- src/packages/site/definitions/raingfh.ts
> fix(pkg/site): raingfh 缺少 User 等级

- src/entries/options/views/Overview/MyData/UserDataTimeline/utils.ts
refs: https://github.com/pt-plugins/PT-depiler/issues/468
> fix(UserDataTimeline): improve user info logic for failed site data

- src/entries/options/views/Overview/MyData/UserDataStatistic/utils.ts
UserDataStatistic 组件在显示统计数据时，会包含已经从配置中删除的站点数据，这可能导致UI显示不准确的信息。
在 `loadFullData` 方法中添加了站点过滤逻辑：
1. **导入必要的依赖**：添加了 `useMetadataStore` 导入
2. **提前过滤数据**：使用 `metadataStore.getAddedSiteIds` 在数据处理前就过滤掉已删除的站点
3. **性能优化**：避免了在循环中使用 `continue` 跳过删除的站点，直接在数据源头过滤
4. **边界情况处理**：当没有有效站点数据时，提前返回空结果
5. **调试支持**：添加了日志记录被过滤掉的站点数量
- **更好的性能**：提前过滤避免了后续不必要的计算
- **类型安全**：明确的类型注解
- **可观测性**：添加调试日志帮助问题排查
- **代码可读性**：清晰的注释说明
- ✅ TypeScript 类型检查通过
- ✅ 项目构建成功
- ✅ 代码格式化通过
解决了UserDataStatistic中显示已删除站点数据的问题。
> fix(UserDataStatistic): 从UI中移除已经删掉的站点

- src/packages/site/definitions/redacted.ts
- src/packages/site/schemas/GazelleJSONAPI.ts
Introduce an uploads selector to the GazelleJSONAPI for enhanced data handling.
> feat(pkg/site): 添加上传数据选择器到GazelleJSONAPI

- src/entries/options/views/Overview/SearchEntity/Index.vue
- src/locales/en.json
- src/locales/zh_CN.json
Enhance the search status display by providing progress updates and additional context when results are received. This includes new translations for both English and Chinese.
> feat(SearchEntity): 更新搜索状态提示，添加搜索进度信息
