pt-plugins/PT-depiler

src/packages/site/definitions/hhanclub.ts
The selector for bonusPerHour has been changed to `.grid .row-span-4` for the hhanclub site to correctly parse the bonus points information.
=> Fix(hhanclub): Update bonusPerHour selector

src/packages/site/schemas/Unit3D.ts
- I updated the tags array in `src/packages/site/schemas/Unit3D.ts`.
- The new tags include 'Free', '2xUp', '75%', '50%', and '25%'.
- I updated the selectors according to your specifications.
- I referenced the colors from `NexusPHP.ts`, using defaults for any unmatched tags.
=> fix(u3d): #138 free tags

src/entries/options/views/Overview/DownloadHistory/Index.vue, src/entries/options/views/Overview/MediaServerEntity/Index.vue, src/entries/options/views/Overview/MyData/Index.vue, src/entries/options/views/Overview/SearchEntity/Index.vue, src/entries/options/views/Overview/SearchResultSnapshot/Index.vue, src/entries/options/views/Settings/SetBackup/Index.vue, src/entries/options/views/Settings/SetBase/BackupWindow.vue, src/entries/options/views/Settings/SetBase/DownloadWindow.vue, src/entries/options/views/Settings/SetBase/SearchEntityWindow.vue, src/entries/options/views/Settings/SetBase/SocialInformationWindow.vue, src/entries/options/views/Settings/SetBase/UserInfoWindow.vue, src/entries/options/views/Settings/SetSearchSolution/Index.vue, src/entries/options/views/Settings/SetSite/Index.vue, src/entries/options/views/Settings/SetSite/OneClickImportDialog.vue, src/locales/en.json, src/locales/zh_CN.json
- 没有完整覆盖所有的代码
- 可能还需要优化i18n文件结构？
---
建议：
1. https://github.com/pt-plugins/PT-depiler/blob/fba9162b1cd4d861d7f48e01c37e93d9650775cf/src/entries/options/plugins/i18n.ts#L34
因为目前中文的翻译覆盖最全，建议fallback到中文
2. 也许可以申请一下 [Hosted Weblate](https://hosted.weblate.org) 来管理i18n翻译
=> extract i18n fields from vue code

src/packages/site/definitions/springsunday.ts
This commit removes the `bonusPerHour` field from the `parseUserInfoForSeedingStatus` method in the `springsunday.ts` site definition file as requested by the user.
=> Remove bonusPerHour from springsunday site definition

src/packages/site/definitions/keepfrds.ts
Introduce the bonusPerHour field to enhance the functionality of the custom selector, allowing for more precise data extraction from user details. This change improves the overall data handling in the site metadata.
=> Add bonusPerHour field for custom selector support

src/packages/site/schemas/NexusPHP.ts
原代码中未匹配时（发种为 0 的情况），经 Number() 转换后为 NaN，不触发 `?? 0`，造成整个表达式的结果非数字。
=> fix(pkg/site): 修复 uploads 可能为 NaN 的问题

src/entries/options/stores/runtime.ts, src/entries/options/views/Overview/SearchEntity/utils.ts, src/entries/shared/types/storages/runtime.ts
- 新增 endAt 字段，精确记录搜索结束时间点。
- 重构 searchCostTime getter，根据搜索状态（进行中/已结束）动态计算耗时，取代原有的累加方式。
- 统一时间戳生成方式为 Date.now()，提升代码一致性。
=> fix(search): 修复搜索耗时计算逻辑，确保时间准确性

src/packages/site/definitions/audiences.ts
- Return 0 for negative progress values instead of negative numbers
- Return ETorrentStatus.unknown for negative progress in torrents-progress2
- Update regex to support negative values parsing for both progress and status selectors
=> fix(audiences): handle negative progress values

src/packages/site/definitions/exoticaz.ts, src/packages/site/schemas/AvistazNetwork.ts, src/packages/site/types/site.ts
应站点要求，不启用用户数据获取
> User information will never be available in any form or API, as we respect the privacy and confidentiality of user information.
@refs: https://github.com/pt-plugins/PT-Plugin-Plus/issues/996#issuecomment-1057856310
仅开启搜索功能 搜索所需token的存储待实现 目前为每次搜索前请求一次 预参考 https://github.com/pt-plugins/PT-depiler/blob/master/src/packages/site/definitions/zhuque.ts#L286-289
=> feat(pkg/site): 适配 Exoticaz

src/entries/options/views/Settings/SetBackup/Index.vue, src/locales/en.json, src/locales/zh_CN.json
- 将翻译键从 SetBackup.index.table.enabled 简化为 SetBackup.table.enabled
- 在英文和中文翻译文件中添加对应的翻译
=> fix: 修复SetBackup页面enabled列翻译问题

src/entries/options/views/Settings/SetBackup/RestoreDialog.vue, src/entries/options/views/Settings/SetBase/Index.vue
重构 SetBase/Index.vue，使用计算属性 activeTab 来处理标签页导航，简化了代码逻辑，并确保在直接导航时能正确激活标签页。
在 RestoreDialog.vue 中添加了到 PT-Plugin-Plus 备份导入页面的链接，并修复了相关的路由跳转逻辑。
=> feat: 重构 SetBase 标签页逻辑并修复路由问题

src/packages/site/definitions/opencd.ts, src/packages/site/definitions/ultrahd.ts
同时发现一个问题 可能是站点nphp版本较老的缘故 种子列表页(torrents.php)的下载按钮是不完整的 即`download.php?id=12345` 不带passkey的下载链接导致导出链接和批量功能不可用于下载器 也会影响到插件搜索结果的链接
目前想到方案：
1.  _userInputSettingsMeta_ 有感输入
2.  _[中间层提供实例缓存运行配置等功能](https://github.com/pt-plugins/PT-depiler/commit/d81bb01a98b618e029d776de3d37d03f8b2ecb11)_ 无感获取
=> fix(pkg/site): 修复opencd详情页无content-script完整功能

src/packages/site/schemas/Unit3D.ts
- Add support for sites using dt:contains + dd selector pattern
- Maintain backward compatibility with existing td:contains + td pattern
- Fixes seeding size detection for blu and other Unit3D sites using definition lists
=> fix: support dt/dd structure for Unit3D seeding size selector

src/packages/site/schemas/Unit3D.ts, src/packages/site/utils/filter.ts
修改parseNumber过滤器，使用\s替代单个空格字符来匹配所有类型的空白字符
=> fix: 修复Unit3D站点bonus积分解析错误

src/entries/options/components/ResultParseStatus.vue, src/locales/en.json, src/locales/zh_CN.json, src/packages/site/schemas/AbstractBittorrentSite.ts, src/packages/site/schemas/AbstractPrivateSite.ts, src/packages/site/types/base.ts, src/packages/site/types/site.ts
效果如下：
对于 CF 盾，不再显示为“需要登录”，可以进行区分，减少误解
=> feat(MyData): 新增解析状态 EResultParseStatus.CFBlocked 并改进提示

src/locales/en.json, src/locales/zh_CN.json
引导用户可以尝试“手动访问一次站点”，以获取有效的 `cf_clearance`
=> feat(i18n): 优化出现 CFBlock 错误时的提示

src/entries/background/utils/cookies.ts, src/entries/offscreen/utils/userInfo.ts, src/entries/options/stores/config.ts, src/entries/options/views/Settings/SetBase/UserInfoWindow.vue, src/entries/shared/types/storages/config.ts, src/locales/en.json, src/locales/zh_CN.json
核心功能实现：
- 在配置架构中新增autoExtendCookies配置项，包含enabled/triggerThreshold/extensionDuration选项
- 实现calculateRemainingDays()函数计算cookie剩余有效期
- 实现checkAndExtendCookies()函数检查并延长即将过期的cookies
- 将cookie延长逻辑集成到用户信息刷新流程(getSiteUserInfoResult)中
技术细节：
- 使用date-fns库进行日期计算，确保时间处理的准确性
- 支持可配置的触发阈值(1-10周)和延长时长(1-12个月)
- 实现静默错误处理机制，确保cookie延长失败不影响用户信息获取流程
- 跳过session cookies处理，只处理有明确过期时间的cookies
- 使用chrome.cookies API进行cookie操作
用户界面优化：
- 在用户信息设置页面添加自动延长cookies配置选项
- 实现动态标签显示，开关标签直接显示当前配置值
- 移除冗余的功能状态显示和帮助文本，简化界面
- 优化配置项文本："触发延长的时间阈值" → "当cookies剩余有效期少于"
- 优化配置项文本："延长时长" → "自动延长其有效期"
国际化支持：
- 添加中文(zh-CN)和英文(en)本地化文本
- 支持动态参数传递，显示具体的配置数值
- 文本表述更加直观易懂
工作流程集成：
- 在用户信息刷新前自动检查并延长cookies
- 异步执行，不阻塞主要的用户信息获取流程
- 错误日志记录，便于问题排查和调试
- 与现有的用户信息自动刷新功能完美兼容
配置存储：
- 默认配置：功能关闭，触发阈值2周，延长时长3个月
- 配置持久化存储，支持用户自定义设置
- 配置验证，确保参数在有效范围内
=> feat(cookies): 添加自动延长cookies功能及相关配置

src/packages/site/definitions/asiancinema.ts, src/packages/site/definitions/beyondhd.ts, src/packages/site/definitions/blutopia.ts, src/packages/site/definitions/broadcasthenet.ts, src/packages/site/definitions/huno.ts, src/packages/site/definitions/torrentleech.ts
Introduce default H&R tags for global H&R sites and update their color to red, enhancing visibility and searchability.
=> feat: add default H&R tags with red color for global sites

src/packages/mediaServer/entity/plex.ts
item.key的值包含且以'/children'结尾导致剧集链接访问一直加载中
正常能访问的链接
=> fix: 修复媒体库plex剧集访问链接

src/entries/options/stores/config.ts, src/entries/options/utils.ts, src/entries/options/views/Overview/MyData/Index.vue, src/entries/options/views/Overview/MyData/UserLevelShowSpan.vue, src/entries/shared/types/storages/config.ts, src/locales/en.json, src/locales/zh_CN.json
为MyData表格添加数字简化显示功能，使用国际标准缩写（K/M/B/T）替代长数字，提升用户体验。
- **数字简化显示**: 支持 K/M/B/T 国际缩写格式
- **智能小数处理**: 整数不显示小数，非整数保留2位小数
- **用户控制**: 可通过设置菜单开启/关闭功能
- 仅应用于 `bonus` 和 `seedingBonus` 字段
- 覆盖 `MyData/Index.vue` 和 `UserLevelShowSpan.vue` 组件
- 新增 `simplifyNumbers` 配置选项
- 实现优化的 `simplifyNumber` 工具函数
- 数组驱动的循环结构，易于维护
- 完整的 TypeScript 类型支持
- 添加中文翻译: \"简化数字显示\"
- 添加英文翻译: \"Simplify Numbers\"
- ✅ 类型检查通过
- ✅ 构建成功
- ✅ 功能测试完成
- ✅ 国际化文本正确
- 向后兼容，默认关闭新功能
- 不影响现有数据显示逻辑
- 用户可自由选择开启或关闭
=> feat: 为MyData表格添加bonus数字简化功能

README.md, patches/git-rev-sync.patch, pnpm-lock.yaml, pnpm-workspace.yaml, vite.config.ts
鉴于 git-rev-sync 库已经不更新，我们可以考虑直接使用 pnpm patch <package> 的方式，拓展 `git.count()` 方法。实现 commmit count 在 action/checkout 的 fetch-depth:0 条件下，不受其他分支的影响。
refs: https://github.com/kurttheviking/git-rev-sync-js/pull/64
closed: https://github.com/pt-plugins/PT-depiler/pull/385
=> feat(git-rev-sync): enhance git.count() function

src/packages/site/schemas/NexusPHP.ts, src/packages/site/utils/datetime.ts
能够正确处理的情况：
✅ 前后有空格：" 2024-01-15 " → 正确解析
✅ 简单前缀文字："Date: 2024-01-15" → 正确解析
✅ 某些英文前缀："Time is 2024-01-15 10:30:00" → 正确解析
✅ 后缀括号："2024-01-15 (updated)" → 正确解析
✅ 时区标识："2024-01-15 10:30:00 GMT" → 正确解析
无法处理的情况：
❌ 复杂描述："Published on 2024-01-15 at 10:30" → 解析失败
❌ 中文字符："发布时间：2024-01-15" → 解析失败
❌ 无效格式："2024-13-45" → 解析失败
=> fix(datetime): 增加对常见日期格式的原生处理支持

src/entries/options/views/Overview/MyData/UserLevelRequirementsTd.vue, src/entries/options/views/Overview/MyData/UserLevelShowSpan.vue, src/entries/options/views/Overview/MyData/UserLevelsComponent.vue, src/entries/options/views/Overview/MyData/UserNextLevelUnMet.vue
错误如图：
其中：
第二个图的问题已经完全修复。
第一个图中，排查到此情境下 formatDuration 函数的传入参数 duration 为 "P"，而不是预期的 "P0D"，没有追到原因，故仅做了临时性修补。
=> fix(UserLevelRequirementsTd): 修复 Interval 和 Date 相互转换的错误

src/entries/options/views/Overview/SearchEntity/AdvanceFilterGenerateDialog.vue, src/entries/options/views/Overview/SearchEntity/utils.ts, src/locales/en.json, src/locales/zh_CN.json, src/packages/site/types/torrent.ts
为搜索结果添加种子状态过滤功能，支持按照种子的下载状态进行筛选。
- 在 keywords 数组中添加 status 关键字支持
- 实现状态值的中文化显示转换：
- 未知 (ETorrentStatus.unknown = 0)
- 下载中 (ETorrentStatus.downloading = 1) 
- 做种中 (ETorrentStatus.seeding = 2)
- 未活动 (ETorrentStatus.inactive = 3)
- 已完成 (ETorrentStatus.completed = 4)
- 添加对 undefined 状态值的处理，统一转换为 未知 状态
- 新增 statusOptions 配置数组，包含所有状态选项
- 为每个状态配置对应的图标和颜色：
- 未知：mdi-help (grey)
- 下载中：mdi-arrow-down (info/blue)
- 做种中：mdi-arrow-up (success/green)
- 未活动：mdi-pause (warning/orange)
- 已完成：mdi-check (success/green)
- 集成到高级过滤器对话框中，支持多选和状态切换
- **框架集成**：基于现有的 useTableCustomFilter 框架实现
- **数据处理**：通过 search-query-parser 解析状态过滤条件  
- **UI组件**：使用 Vuetify 的 Checkbox 组件实现状态选择
- **国际化**：全面支持中文显示，提升用户体验
- ✅ 编译无错误
- ✅ 生产构建成功
- ✅ 状态过滤逻辑正常工作
- ✅ 中文显示正确
- ✅ 与现有过滤器功能无冲突
用户现在可以通过直观的中文状态标签来筛选种子：
- 快速找到正在做种的资源
- 筛选下载中的任务
- …
=> feat(SearchEntity): 添加种子状态选项并更新过滤器逻辑

src/entries/content-script/app/components/AdvanceListModuleDialog.vue
基于 ETorrentStatus 进行判断，防止大量推送已经在做种或者正在下载中的种子
=> feat(AdvanceListModule): 增加勾选未下载的种子功能

src/entries/options/views/Overview/MyData/UserDataTimeline/Index.vue, src/entries/options/views/Overview/MyData/UserDataTimeline/utils.ts, src/entries/options/views/Overview/MyData/utils.ts
为离线站点添加 mdi-signal-off 图标标识，以区分不同的站点状态。
- **扩展站点元数据结构**：在 `ITimelineSiteMetadata` 接口中添加 `isOffline` 属性
- **增加统计数据**：在时间轴数据中添加离线站点数量统计
- **UI图标显示**：在站点选择区域为离线站点显示 mdi-signal-off 图标
- **状态区分**：只对离线但非dead的站点显示图标，以区分不同状态类型
- **合适的颜色**：使用 blue-grey-darken-1 颜色来恰当表示'无信号'状态
1. `src/entries/options/views/Overview/MyData/utils.ts`
- 扩展 `ITimelineSiteMetadata` 接口添加 `isOffline` 属性
- 在 `loadAllAddedSiteMetadata` 函数中添加获取离线状态的逻辑
2. `src/entries/options/views/Overview/MyData/UserDataTimeline/utils.ts`
- 在 `ITimelineData.totalInfo` 中添加 `offlineSites` 统计
- 添加离线站点数量的计算逻辑
3. `src/entries/options/views/Overview/MyData/UserDataTimeline/Index.vue`
- 在站点选择区域添加条件渲染的 `v-icon` 组件
- 使用条件判断确保只对离线非dead站点显示
- **图标选择**：使用 Material Design Icons 的 `mdi-signal-off` 图标，语义明确表示无信号状态
- **颜色选择**：使用 `blue-grey-darken-1` …
=> feat: Add offline site indicator with mdi-signal-off icon

src/entries/background/utils/contextMenus.ts
此PR增强了右键菜单的下载功能，在通过右键菜单发送种子到下载器时，现在会包含页面标题和URL作为元数据。
- 为 `downloadLinkPush` 函数添加了 `title` 和 `url` 参数
- 在调用下载功能时传递当前标签页的标题和URL
- 为种子下载提供更多的上下文信息
- `src/entries/background/utils/contextMenus.ts`
1. **函数签名更新**: `downloadLinkPush` 函数现在接受可选的 `title` 和 `url` 参数
2. **种子对象增强**: 传递给下载器的种子对象现在包含标题和URL信息
3. **调用点更新**: 所有调用 `downloadLinkPush` 的地方都已更新以传递标签页元数据
- 新增的参数都是可选的，确保向后兼容
- 不会破坏现有的下载功能
- 提供更丰富的种子元数据给下载器
- 便于用户在下载器中识别种子来源
- 改善整体用户体验
请测试以下场景：
此更改改进了右键菜单功能，为种子下载提供了更好的上下文信息。
=> feat(contextMenus): 增强右键菜单下载功能，添加标题和URL元数据支持

src/entries/options/stores/config.ts, src/entries/options/views/Overview/DownloadHistory/Index.vue
此PR移除了下载历史表格中的"№"列，并优化了相关的排序配置，提升用户体验和界面简洁性。
- **移除下载历史表格中的"№"列**：该列对用户价值有限，移除后界面更加简洁
- 保持所有现有功能正常工作（选择、操作等）
- **默认排序改进**：从按ID排序改为按下载时间排序，更符合用户使用习惯
- **智能配置清理**：自动处理已保存的基于ID字段的排序配置
- **智能清理机制**：自动检测并移除基于`id`字段的排序配置
- **多重排序支持**：只移除`id`排序项，保留用户设置的其他有效排序
- **平滑迁移**：确保现有用户的排序偏好得到妥善处理
1. `src/entries/options/views/Overview/DownloadHistory/Index.vue`
- 从`tableHeader`中移除`{ title: "№", key: "id", align: "center" }`
2. `src/entries/options/stores/config.ts`
- 默认排序配置：`{ key: "id", order: "desc" }` → `{ key: "downloadAt", order: "desc" }`
- 添加`afterRestore`钩子中的智能清理逻辑
- ✅ **选择功能**：继续使用`item-value="id"`，多选功能正常
- ✅ **过滤功能**：基于`filter-keys="['id']"`，不受影响  
- ✅ **操作功能**：重新下载、删除等基于`item.id`，完全正常
- ✅ **排序功能**：现在默认按下载时间排序，更有意义
- **单一ID排序**：`[{ key: "id", order: "desc" }]` → `[{ key: "downloadAt", order: …
=> refactor: 移除下载历史表格№列并优化排序配置

src/entries/options/views/Overview/SearchEntity/Index.vue, src/locales/en.json, src/locales/zh_CN.json
在搜索结果页面的v-data-table上方添加了选中种子的统计信息显示，方便用户了解选择了多少个种子和总体积。
- 在v-data-table上方新增统计信息条，只在有选中种子时显示
- 使用单个v-chip组件显示，内部用分隔符分开选中数量和总大小
- 采用info色调的v-alert作为容器，保持界面一致性
- 使用Map数据结构缓存种子数据，避免重复遍历
- 计算选中种子信息时采用增量算法，只遍历选中项
- 从O(n²)复杂度优化到O(n)，解决了大量种子选择时的性能问题
- 新增`torrentDataMap`计算属性缓存种子基础数据
- 新增`selectedTorrentsInfo`计算属性实时计算选中统计
- 使用Vue 3 Composition API的reactive特性确保数据同步
- 支持中英文本地化，添加了相应的翻译键
- ✅ 开发环境验证功能正常
- ✅ 生产构建测试通过
- ✅ 性能优化后选择大量种子无卡顿
- ✅ 中英文界面显示正常
- 仅影响搜索结果页面的UI显示
- 不影响现有功能逻辑
- 向后兼容，不会破坏现有用户体验
统计信息条会在表格上方显示类似：
`🗸 已选择 5 个种子 | 💾 1.2 GB`
=> feat(SearchEntity): 添加搜索结果中选中种子的统计信息
